target-version = "py311"
line-length = 100
fix = true

select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "W",  # pycodestyle warnings
  "I",  # isort
  "N",  # pep8-naming
  "UP", # pyupgrade
  "B",  # bugbear
  "C4", # flake8-comprehensions
  "T20",# flake8-print
  "SIM",# flake8-simplify
  "ARG",# flake8-unused-arguments
  "PL", # pylint
  "PIE",# flake8-pie
  "PTH",# flake8-use-pathlib
  "RUF" # ruff-specific
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[per-file-ignores]
"src/scipaper/api/dependencies.py" = ["B008"]
"src/scipaper/cli.py" = ["E501", "PLC0415", "SIM102", "PLR2004", "N806", "B904"]
"src/scipaper/core/advanced_search.py" = ["PLR0913", "E501", "B904", "SIM108", "SIM103"]
"src/scipaper/core/fetcher.py" = ["UP038", "E501", "B023", "B904", "PLR0912", "RUF013", "PLC0415"]
"src/scipaper/core/recommendations.py" = ["PLR0913", "E501", "B904"]
"src/scipaper/core/recommendations.py" = ["PLR0913", "E501", "B904", "PLR2004"]
"src/scipaper/core/monitoring.py" = ["PLC0415"]
